language: android
dist: trusty
jdk: oraclejdk8

if: branch = master OR type = pull_request

before_install:
  # Download SDK
  - yes | sdkmanager "tools" &>/dev/null
  - yes | sdkmanager "platform-tools" &>/dev/null
  - yes | sdkmanager "build-tools;30.0.2" &>/dev/null
  - yes | sdkmanager "platforms;android-30" &>/dev/null
  # Update remaining dependencies and accept licenses
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null
  # Append suffix -SNAPSHOT
  - sed -ie "s/MATERIAL_PREFERENCE_VERSION.*$/&-SNAPSHOT/g" gradle.properties
  # Copy keystore files
  - echo "$DEBUG_KEYSTORE_FILE_BASE_64" | base64 --decode > "$HOME/.android/debug.keystore"
  - echo "$RELEASE_KEYSTORE_FILE_BASE_64" | base64 --decode > sample/keystore.jks
  - touch local.properties
  - echo "storePassword=$RELEASE_KEYSTORE_STORE_PASSWORD" >> local.properties
  - echo "keyAlias=$RELEASE_KEYSTORE_KEY_ALIAS" >> local.properties
  - echo "keyPassword=$RELEASE_KEYSTORE_KEY_PASSWORD" >> local.properties

script: ./gradlew clean build --stacktrace

after_success:
  - ./.buildscript/deploy_snapshot.sh

env:
  global:
    - ANDROID_SDK_ROOT=/usr/local/android-sdk/

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache